/**
 * Comprehensive SEO Optimization for EASYIO Technologies
 * 300+ keywords targeting Kashmir, J&K, Srinagar, and global markets
 * Organized by search intent and service categories
 */

export const seoKeywords = {
  // Primary Brand Keywords
  brand: [
    "easyio technologies",
    "easyio",
    "easyio tech",
    "easyio kashmir",
    "easyio srinagar",
    "easyio jammu kashmir",
    "easyio J&K",
  ],

  // Best/Top Intent Keywords (High-value local searches)
  bestTopIntent: [
    "best software company in kashmir",
    "best software company in srinagar",
    "best it company in kashmir",
    "best web development company in kashmir",
    "best app development company in kashmir",
    "best software development company in kashmir",
    "top software company in srinagar",
    "top it company in srinagar",
    "top web development company in srinagar",
    "top mobile app development company in srinagar",
    "best erp software company in kashmir",
    "best erp company in srinagar",
    "best custom software company in kashmir",
    "best startup software company in srinagar",
    "best website designer in srinagar",
    "best website designer in kashmir",
    "best web design company in kashmir",
    "best IT company kashmir",
    "top software company kashmir",
    "leading software company kashmir",
    "premium software company kashmir",
    "professional software company kashmir",
    "best software company J&K",
    "top IT company J&K",
    "best developers kashmir",
    "best programmers srinagar",
    "best coding company kashmir",
    "best tech company kashmir",
    "best digital company srinagar",
    "best software agency kashmir",
  ],

  // Near Me + Locality Keywords (High conversion intent)
  nearMeLocality: [
    // Core "near me" keywords
    "software company near me",
    "it company near me",
    "web developer near me",
    "website development near me",
    "mobile app developer near me",
    "erp software near me",
    "crm software near me",
    "software company near me in srinagar",
    "it company near me srinagar",
    "web developer near me srinagar",
    "app developer near me srinagar",
    "erp software developers near me in srinagar",
    // Lal Chowk
    "software company in lal chowk",
    "it company in lal chowk",
    "web development lal chowk",
    "app development lal chowk",
    "erp software developers in lal chowk",
    // Karan Nagar
    "software company in karan nagar",
    "it company karan nagar",
    "web development karan nagar",
    "software developers karan nagar",
    // Raj Bagh
    "software company in raj bagh",
    "it company raj bagh",
    "web development raj bagh",
    "erp software developers in raj bagh",
    // Batamaloo
    "software company in batamaloo",
    "it company batamaloo",
    "web development batamaloo",
    // Nowgam
    "software company in nowgam",
    "it company nowgam",
    "software developers nowgam",
    // Dalgate
    "software company in dalgate",
    "it company dalgate",
    "web development dalgate",
    // Bemina
    "software company in bemina",
    "it company bemina",
    "erp software developers in bemina",
    "web development bemina",
    // Jawahar Nagar
    "software company in jawahar nagar srinagar",
    "it company jawahar nagar",
    "web development jawahar nagar",
    // Sanat Nagar
    "software company in sanat nagar",
    "it company sanat nagar",
    "software developers sanat nagar",
    // Hyderpora
    "software company hyderpora",
    "it company hyderpora",
    // Sonwar
    "software company sonwar",
    "it company sonwar",
    // Rainawari
    "software company rainawari",
    "web development rainawari",
    // Hazratbal
    "software company hazratbal",
    "it company hazratbal",
  ],

  // ERP Keywords (General + Modules)
  erp: [
    // General ERP
    "erp software kashmir",
    "erp software srinagar",
    "erp system development kashmir",
    "erp implementation services srinagar",
    "erp customization company kashmir",
    "cloud erp kashmir",
    "erp solution provider srinagar",
    "enterprise software company kashmir",
    "erp software J&K",
    "custom erp development kashmir",
    "erp consulting kashmir",
    "erp integration srinagar",
    "erp migration kashmir",
    "affordable erp kashmir",
    "small business erp srinagar",
    // ERP Modules
    "hrms software srinagar",
    "hrms software kashmir",
    "payroll software kashmir",
    "payroll software srinagar",
    "attendance management system srinagar",
    "attendance management system kashmir",
    "inventory management software kashmir",
    "inventory management software srinagar",
    "billing software srinagar",
    "billing software kashmir",
    "accounting software integration kashmir",
    "accounting software srinagar",
    "purchase management system kashmir",
    "purchase management system srinagar",
    "sales management system kashmir",
    "sales management system srinagar",
    "warehouse management system kashmir",
    "warehouse management system srinagar",
    "crm erp integration kashmir",
    "crm erp integration srinagar",
    "erp with mobile app kashmir",
    "erp dashboard analytics kashmir",
    "supply chain management software kashmir",
    "asset management software srinagar",
    "project management erp kashmir",
    "manufacturing erp kashmir",
    "distribution erp srinagar",
    // Brand-specific ERP
    "sap erp developers srinagar",
    "sap erp developers kashmir",
    "sap erp consultant srinagar",
    "oracle erp developers kashmir",
    "microsoft dynamics kashmir",
    "odoo developers srinagar",
    "odoo implementation kashmir",
  ],

  // App Development Keywords
  appDevelopment: [
    "mobile app development company kashmir",
    "mobile app developer srinagar",
    "android app development srinagar",
    "android app development kashmir",
    "ios app development kashmir",
    "ios app development srinagar",
    "flutter app development kashmir",
    "flutter app development srinagar",
    "react native app development srinagar",
    "react native app development kashmir",
    "app maintenance services kashmir",
    "app maintenance srinagar",
    "ui ux design for mobile apps srinagar",
    "ui ux design mobile apps kashmir",
    "ecommerce app development kashmir",
    "ecommerce app development srinagar",
    "booking app development kashmir",
    "booking app development srinagar",
    "delivery app development srinagar",
    "delivery app development kashmir",
    "taxi app development kashmir",
    "taxi app development srinagar",
    "school app development srinagar",
    "school app development kashmir",
    "hospital app development kashmir",
    "hospital app development srinagar",
    "food delivery app kashmir",
    "restaurant app development srinagar",
    "fitness app development kashmir",
    "social media app development srinagar",
    "chat app development kashmir",
    "on-demand app development kashmir",
    "hybrid app development srinagar",
    "cross-platform app development kashmir",
    "native app development srinagar",
    "app redesign services kashmir",
    "app modernization srinagar",
    "app testing services kashmir",
    "app store optimization kashmir",
    "play store optimization srinagar",
  ],

  // Website / Web App / E-commerce Keywords
  webDevelopment: [
    "website development company kashmir",
    "web development company srinagar",
    "web development company kashmir",
    "web design company kashmir",
    "web design company srinagar",
    "responsive website design srinagar",
    "responsive website design kashmir",
    "seo friendly website development kashmir",
    "seo friendly website srinagar",
    "ecommerce website development kashmir",
    "ecommerce website development srinagar",
    "ecommerce development srinagar",
    "ecommerce development kashmir",
    "shopify development srinagar",
    "shopify development kashmir",
    "wordpress development srinagar",
    "wordpress development kashmir",
    "custom web application development kashmir",
    "custom web application srinagar",
    "react js development srinagar",
    "react js development kashmir",
    "next js development kashmir",
    "next js development srinagar",
    "landing page design srinagar",
    "landing page design kashmir",
    "website redesign services kashmir",
    "website redesign srinagar",
    "website maintenance srinagar",
    "website maintenance kashmir",
    "website hosting kashmir",
    "website hosting srinagar",
    "static website development kashmir",
    "dynamic website development srinagar",
    "cms development kashmir",
    "content management system srinagar",
    "woocommerce development kashmir",
    "magento development srinagar",
    "laravel development kashmir",
    "php development srinagar",
    "node js development kashmir",
    "vue js development srinagar",
    "angular development kashmir",
    "full stack development srinagar",
    "frontend development kashmir",
    "backend development srinagar",
    "api development kashmir",
    "web portal development srinagar",
    "corporate website kashmir",
    "business website srinagar",
    "portfolio website kashmir",
    "blog website development srinagar",
  ],

  // Industry-Specific Keywords
  industrySpecific: [
    // Education
    "school erp software kashmir",
    "school erp srinagar",
    "school management system srinagar",
    "school management system kashmir",
    "student fee management software kashmir",
    "student fee management srinagar",
    "online attendance system for school kashmir",
    "online attendance system school srinagar",
    "college management software kashmir",
    "university management system srinagar",
    "education erp kashmir",
    "learning management system kashmir",
    "lms development srinagar",
    "e-learning platform kashmir",
    "online examination system kashmir",
    "student information system srinagar",
    // Hospital/Clinic
    "hospital management software kashmir",
    "hospital management system srinagar",
    "clinic management system srinagar",
    "clinic management software kashmir",
    "pharmacy management software kashmir",
    "pharmacy software srinagar",
    "healthcare software kashmir",
    "patient management system srinagar",
    "doctor appointment system kashmir",
    "lab management software srinagar",
    "medical billing software kashmir",
    "telemedicine app kashmir",
    "healthcare app development srinagar",
    // Hotel/Restaurant
    "hotel management software kashmir",
    "hotel management system srinagar",
    "restaurant billing software srinagar",
    "restaurant billing software kashmir",
    "hotel booking system kashmir",
    "restaurant pos kashmir",
    "food ordering system srinagar",
    "hospitality software kashmir",
    "hotel erp srinagar",
    "resort management software kashmir",
    // Retail
    "pos software srinagar",
    "pos software kashmir",
    "inventory billing software kashmir",
    "inventory billing software srinagar",
    "retail erp software kashmir",
    "retail erp srinagar",
    "retail management system kashmir",
    "shop management software srinagar",
    "supermarket software kashmir",
    "grocery store software srinagar",
    "barcode software kashmir",
    // Construction/Real Estate
    "construction erp software kashmir",
    "construction erp srinagar",
    "site reporting app development kashmir",
    "real estate crm software kashmir",
    "real estate crm srinagar",
    "property management software kashmir",
    "real estate website development srinagar",
    "builder software kashmir",
    "contractor management system srinagar",
    // Manufacturing
    "manufacturing software kashmir",
    "manufacturing erp srinagar",
    "production management system kashmir",
    "quality control software srinagar",
    // Transport/Logistics
    "transport management software kashmir",
    "logistics software srinagar",
    "fleet management system kashmir",
    "courier software srinagar",
    // Agriculture
    "agriculture software kashmir",
    "farm management system srinagar",
    "dairy management software kashmir",
  ],

  // Price / Cost / Quotation Keywords (Highest lead intent)
  pricingIntent: [
    "erp software cost in kashmir",
    "erp software price in srinagar",
    "erp software cost srinagar",
    "website development cost in srinagar",
    "website development cost kashmir",
    "ecommerce website cost kashmir",
    "ecommerce website cost srinagar",
    "app development cost srinagar",
    "app development cost kashmir",
    "software development cost kashmir",
    "software development cost srinagar",
    "custom software development pricing india kashmir",
    "custom software pricing kashmir",
    "get quote software company srinagar",
    "get quote software kashmir",
    "hire developers in srinagar",
    "hire developers kashmir",
    "monthly website maintenance cost srinagar",
    "monthly website maintenance cost kashmir",
    "affordable website design kashmir",
    "affordable app development srinagar",
    "cheap software development kashmir",
    "budget software company srinagar",
    "software development rates kashmir",
    "web design pricing srinagar",
    "mobile app development pricing kashmir",
    "erp implementation cost srinagar",
    "hourly rate developers kashmir",
    "freelance developers srinagar",
    "outsource development kashmir",
  ],

  // Trust Keywords (Buyer validation queries)
  trustIntent: [
    "software company with portfolio in srinagar",
    "software company with portfolio kashmir",
    "software company with reviews in kashmir",
    "software company reviews srinagar",
    "iso certified software company kashmir",
    "trusted software company in srinagar",
    "trusted software company kashmir",
    "professional software developers kashmir",
    "professional developers srinagar",
    "enterprise software solutions kashmir",
    "reliable software company srinagar",
    "experienced developers kashmir",
    "certified developers srinagar",
    "award winning software company kashmir",
    "reputed it company srinagar",
    "established software firm kashmir",
    "software company testimonials kashmir",
    "client reviews software company srinagar",
    "case studies software kashmir",
    "software company track record srinagar",
  ],

  // SEO + Digital Presence Keywords
  seoDigital: [
    "seo services srinagar",
    "seo services kashmir",
    "seo company srinagar",
    "seo company kashmir",
    "search engine optimization services near me srinagar",
    "search engine optimization kashmir",
    "digital marketing srinagar",
    "digital marketing kashmir",
    "social media marketing srinagar",
    "social media marketing kashmir",
    "google ads management kashmir",
    "ppc services srinagar",
    "content marketing kashmir",
    "email marketing srinagar",
    "online marketing kashmir",
    "brand marketing srinagar",
    "local seo kashmir",
    "local seo srinagar",
  ],

  // Location-Based Keywords (Kashmir/J&K Focus)
  location: [
    "software company in kashmir",
    "software company srinagar",
    "IT company kashmir",
    "IT company srinagar",
    "IT company jammu kashmir",
    "tech company kashmir",
    "tech company srinagar",
    "software development kashmir",
    "software development srinagar",
    "custom software kashmir",
    "custom software srinagar",
    "digital solutions kashmir",
    "digital solutions srinagar",
    "technology solutions kashmir",
    "technology solutions srinagar",
    "software services kashmir",
    "software services srinagar",
    "IT services kashmir",
    "IT services srinagar",
    "tech solutions kashmir",
    "tech solutions srinagar",
    "software firm kashmir",
    "software firm srinagar",
    "IT firm kashmir",
    "IT firm srinagar",
    "technology company J&K",
    "software company J&K",
    "IT company J&K",
    "web development J&K",
    "app development J&K",
    "software company jammu",
    "it company jammu",
    "web development jammu",
  ],

  // Service-Based Keywords (General)
  services: [
    "web development",
    "web development services",
    "website development",
    "website creation",
    "best website creators",
    "website builders",
    "custom website development",
    "responsive web design",
    "web application development",
    "app development",
    "mobile app development",
    "iOS app development",
    "Android app development",
    "custom app development",
    "software development",
    "custom software development",
    "enterprise software development",
    "ERP solutions",
    "ERP development",
    "custom ERP solutions",
    "ERP implementation",
    "enterprise resource planning",
    "business software solutions",
    "enterprise architecture",
    "digital transformation",
    "digital solutions",
    "technology consulting",
    "IT consulting",
    "software consulting",
    "cloud solutions",
    "cloud development",
    "API development",
    "backend development",
    "frontend development",
    "full stack development",
    "e-commerce development",
    "e-commerce solutions",
    "online store development",
    "CMS development",
    "content management systems",
    "database development",
    "database solutions",
    "system integration",
    "software integration",
    "API integration",
    "third-party integration",
    "maintenance and support",
    "software maintenance",
    "technical support",
    "UI/UX design",
    "user interface design",
    "user experience design",
    "graphic design",
    "logo design",
    "brand identity",
  ],

  // Technical Keywords
  technical: [
    "React development",
    "Next.js development",
    "Node.js development",
    "Python development",
    "JavaScript development",
    "TypeScript development",
    "Java development",
    "PHP development",
    "Laravel development",
    "Django development",
    "Flask development",
    "Express.js development",
    "MongoDB development",
    "PostgreSQL development",
    "MySQL development",
    "Firebase development",
    "AWS development",
    "Azure development",
    "Google Cloud development",
    "Docker development",
    "Kubernetes development",
    "microservices architecture",
    "RESTful API development",
    "GraphQL development",
    "serverless development",
    "progressive web apps",
    "PWA development",
    "responsive design",
    "mobile-first design",
    "agile development",
    "scrum development",
    "devops services",
    "CI/CD implementation",
    "quality assurance",
    "software testing",
    "automated testing",
    "performance testing",
    "security testing",
    "cybersecurity",
    "data security",
  ],

  // Long-Tail Keywords
  longTail: [
    "best software company in kashmir for web development",
    "top web development company in srinagar for startups",
    "affordable app development company kashmir",
    "custom ERP solutions for businesses in kashmir",
    "professional website creators in srinagar J&K",
    "experienced IT company in jammu and kashmir",
    "reliable software development services in kashmir",
    "best tech solutions provider in kashmir valley",
    "leading digital transformation company in kashmir",
    "premium software services in srinagar city",
    "trusted technology partner in kashmir",
    "innovative software solutions company kashmir",
    "cutting-edge technology services srinagar",
    "modern web development company kashmir",
    "enterprise software solutions provider kashmir",
    "scalable technology solutions J&K region",
    "cost-effective software development in kashmir",
    "quality software services provider srinagar",
    "expert developers team in kashmir",
    "skilled programmers available srinagar",
    "top-rated software company in kashmir valley",
    "highly rated IT services in srinagar",
    "customer-focused software solutions kashmir",
    "on-time project delivery company kashmir",
    "budget-friendly software solutions srinagar",
    "24/7 software support services kashmir",
    "startup friendly software company srinagar",
    "enterprise level software solutions kashmir",
    "dedicated development team kashmir",
    "offshore development partner kashmir",
  ],

  // Problem-Solving Keywords
  problemSolving: [
    "need a website in kashmir",
    "want to create an app in srinagar",
    "looking for software developers in kashmir",
    "need custom software for business kashmir",
    "require ERP system in srinagar",
    "want digital transformation in kashmir",
    "need web development help in kashmir",
    "looking for app developers in srinagar",
    "require IT services in kashmir",
    "need technology solutions in srinagar",
    "want to modernize business in kashmir",
    "need online presence in kashmir",
    "require e-commerce solution in srinagar",
    "want mobile app for business kashmir",
    "need software maintenance in kashmir",
    "looking for tech support in srinagar",
    "require system integration in kashmir",
    "need API development in srinagar",
    "want cloud migration in kashmir",
    "require database solutions in srinagar",
  ],
};

// Combined keywords array for easy access
export const allKeywords = [
  ...seoKeywords.brand,
  ...seoKeywords.bestTopIntent,
  ...seoKeywords.nearMeLocality,
  ...seoKeywords.erp,
  ...seoKeywords.appDevelopment,
  ...seoKeywords.webDevelopment,
  ...seoKeywords.industrySpecific,
  ...seoKeywords.pricingIntent,
  ...seoKeywords.trustIntent,
  ...seoKeywords.seoDigital,
  ...seoKeywords.location,
  ...seoKeywords.services,
  ...seoKeywords.technical,
  ...seoKeywords.longTail,
  ...seoKeywords.problemSolving,
];

// Primary keywords for meta tags (top 20 most valuable)
export const primaryKeywords = [
  "best software company in kashmir",
  "software company srinagar",
  "web development company kashmir",
  "app development company srinagar",
  "erp software kashmir",
  "IT company J&K",
  "best website designers srinagar",
  "mobile app development kashmir",
  "custom software development srinagar",
  "digital transformation kashmir",
  "easyio technologies",
  "top it company kashmir",
  "software company near me srinagar",
  "best erp company kashmir",
  "website development cost kashmir",
  "enterprise software solutions J&K",
  "school erp software kashmir",
  "hospital management software srinagar",
  "ecommerce website development kashmir",
  "flutter app development srinagar",
];

// Srinagar Localities with coordinates for Local SEO
export const srinigarLocalities = [
  {
    name: "Lal Chowk",
    slug: "lal-chowk",
    coordinates: { lat: "34.0747", lng: "74.7975" },
    pincode: "190001",
  },
  {
    name: "Karan Nagar",
    slug: "karan-nagar",
    coordinates: { lat: "34.0921", lng: "74.7920" },
    pincode: "190010",
  },
  {
    name: "Raj Bagh",
    slug: "raj-bagh",
    coordinates: { lat: "34.0847", lng: "74.8089" },
    pincode: "190008",
  },
  {
    name: "Batamaloo",
    slug: "batamaloo",
    coordinates: { lat: "34.0541", lng: "74.7856" },
    pincode: "190009",
  },
  {
    name: "Nowgam",
    slug: "nowgam",
    coordinates: { lat: "33.9997", lng: "74.8028" },
    pincode: "190015",
  },
  {
    name: "Dalgate",
    slug: "dalgate",
    coordinates: { lat: "34.0802", lng: "74.8411" },
    pincode: "190001",
  },
  {
    name: "Bemina",
    slug: "bemina",
    coordinates: { lat: "34.0616", lng: "74.7527" },
    pincode: "190018",
  },
  {
    name: "Jawahar Nagar",
    slug: "jawahar-nagar",
    coordinates: { lat: "34.1014", lng: "74.7925" },
    pincode: "190008",
  },
  {
    name: "Sanat Nagar",
    slug: "sanat-nagar",
    coordinates: { lat: "34.0306", lng: "74.8023" },
    pincode: "190005",
  },
  {
    name: "Hyderpora",
    slug: "hyderpora",
    coordinates: { lat: "34.0161", lng: "74.8197" },
    pincode: "190014",
  },
  {
    name: "Sonwar",
    slug: "sonwar",
    coordinates: { lat: "34.0821", lng: "74.8159" },
    pincode: "190001",
  },
  {
    name: "Rainawari",
    slug: "rainawari",
    coordinates: { lat: "34.0969", lng: "74.8231" },
    pincode: "190003",
  },
  {
    name: "Hazratbal",
    slug: "hazratbal",
    coordinates: { lat: "34.1267", lng: "74.8422" },
    pincode: "190006",
  },
];

// Location data for local SEO
export const locationData = {
  name: "EASYIO Technologies",
  address: {
    streetAddress: "Srinagar",
    addressLocality: "Srinagar",
    addressRegion: "Jammu and Kashmir",
    postalCode: "190001",
    addressCountry: "IN",
  },
  geo: {
    latitude: "34.0837",
    longitude: "74.7973",
  },
  areaServed: [
    "Kashmir",
    "Srinagar",
    "Jammu and Kashmir",
    "J&K",
    "Lal Chowk",
    "Karan Nagar",
    "Raj Bagh",
    "Batamaloo",
    "Nowgam",
    "Dalgate",
    "Bemina",
    "Jawahar Nagar",
    "Sanat Nagar",
    "Hyderpora",
    "Sonwar",
    "Rainawari",
    "Hazratbal",
    "India",
    "Global",
  ],
  openingHours: "Mo-Fr 09:00-18:00",
  telephone: "+91-XXXXXXXXXX",
  email: "info@easyio.tech",
  url: "https://easyio.tech",
};

// Expanded Service categories for structured data
export const serviceCategories = [
  {
    name: "Web Development",
    slug: "web-development",
    description: "Custom website and web application development services in Kashmir. Responsive, SEO-friendly websites using React, Next.js, and modern technologies.",
    keywords: ["website development kashmir", "web design srinagar", "responsive website kashmir"],
  },
  {
    name: "Mobile App Development",
    slug: "app-development",
    description: "Professional mobile app development for iOS and Android in Kashmir. Flutter, React Native, and native app development services.",
    keywords: ["mobile app development kashmir", "android app srinagar", "ios app kashmir"],
  },
  {
    name: "ERP Solutions",
    slug: "erp-solutions",
    description: "Custom ERP development and implementation services in Kashmir. HRMS, payroll, inventory, billing, and complete enterprise resource planning systems.",
    keywords: ["erp software kashmir", "custom erp srinagar", "enterprise software J&K"],
  },
  {
    name: "E-commerce Development",
    slug: "ecommerce-development",
    description: "Complete e-commerce solutions for businesses in Kashmir. Shopify, WooCommerce, custom e-commerce platforms with payment integration.",
    keywords: ["ecommerce development kashmir", "online store srinagar", "shopify kashmir"],
  },
  {
    name: "Digital Transformation",
    slug: "digital-transformation",
    description: "End-to-end digital transformation services for businesses in Kashmir. Modernize your business with cloud solutions and automation.",
    keywords: ["digital transformation kashmir", "business automation srinagar", "cloud migration J&K"],
  },
  {
    name: "Cloud Solutions",
    slug: "cloud-solutions",
    description: "Cloud infrastructure and services for businesses in Kashmir. AWS, Azure, Google Cloud deployment and management.",
    keywords: ["cloud solutions kashmir", "aws services srinagar", "cloud hosting J&K"],
  },
  {
    name: "UI/UX Design",
    slug: "ui-ux-design",
    description: "Professional UI/UX design services in Kashmir. User-centered design for websites and mobile applications.",
    keywords: ["ui ux design kashmir", "website design srinagar", "app design J&K"],
  },
  {
    name: "SEO Services",
    slug: "seo-services",
    description: "Search engine optimization services in Kashmir. Improve your online visibility and rank higher on Google.",
    keywords: ["seo services kashmir", "seo company srinagar", "search optimization J&K"],
  },
  {
    name: "Software Maintenance",
    slug: "software-maintenance",
    description: "Ongoing software maintenance and support services in Kashmir. Bug fixes, updates, and technical support.",
    keywords: ["software maintenance kashmir", "it support srinagar", "technical support J&K"],
  },
  {
    name: "Custom Software Development",
    slug: "custom-software",
    description: "Bespoke software development tailored to your business needs in Kashmir. Scalable and secure custom solutions.",
    keywords: ["custom software kashmir", "bespoke software srinagar", "tailored solutions J&K"],
  },
];

// Industry-specific service data
export const industryServices = [
  {
    industry: "Education",
    slug: "education-software",
    services: [
      { name: "School ERP", slug: "school-erp-software-kashmir", description: "Complete school management system with student records, fees, attendance" },
      { name: "College Management", slug: "college-management-system-kashmir", description: "Higher education management software" },
      { name: "Learning Management System", slug: "lms-development-kashmir", description: "Online learning and course management platform" },
      { name: "Online Examination", slug: "online-examination-system-kashmir", description: "Secure online exam and assessment platform" },
    ],
  },
  {
    industry: "Healthcare",
    slug: "healthcare-software",
    services: [
      { name: "Hospital Management", slug: "hospital-management-software-kashmir", description: "Complete hospital administration and patient management" },
      { name: "Clinic Management", slug: "clinic-management-system-srinagar", description: "Small clinic and doctor practice management" },
      { name: "Pharmacy Management", slug: "pharmacy-management-software-kashmir", description: "Pharmacy inventory and billing system" },
      { name: "Lab Management", slug: "lab-management-software-kashmir", description: "Pathology and diagnostic lab management" },
    ],
  },
  {
    industry: "Hospitality",
    slug: "hospitality-software",
    services: [
      { name: "Hotel Management", slug: "hotel-management-software-kashmir", description: "Hotel booking, reservation, and operations management" },
      { name: "Restaurant POS", slug: "restaurant-billing-software-srinagar", description: "Restaurant billing and order management" },
      { name: "Resort Management", slug: "resort-management-software-kashmir", description: "Resort and tourism business management" },
    ],
  },
  {
    industry: "Retail",
    slug: "retail-software",
    services: [
      { name: "POS Software", slug: "pos-software-srinagar", description: "Point of sale system for retail stores" },
      { name: "Inventory Management", slug: "inventory-management-software-kashmir", description: "Stock and inventory tracking system" },
      { name: "Retail ERP", slug: "retail-erp-software-kashmir", description: "Complete retail business management" },
    ],
  },
  {
    industry: "Construction",
    slug: "construction-software",
    services: [
      { name: "Construction ERP", slug: "construction-erp-software-kashmir", description: "Construction project and resource management" },
      { name: "Real Estate CRM", slug: "real-estate-crm-kashmir", description: "Property management and sales CRM" },
      { name: "Site Reporting", slug: "site-reporting-app-kashmir", description: "Construction site progress reporting app" },
    ],
  },
];

// Expanded FAQ data for FAQ schema (50+ FAQs)
export const faqData = [
  // General Company FAQs
  {
    question: "What services does EASYIO Technologies offer?",
    answer: "EASYIO Technologies offers comprehensive software development services including web development, mobile app development, custom ERP solutions, e-commerce development, digital transformation, cloud solutions, UI/UX design, SEO services, and technology consulting. We are the leading software company in Kashmir serving clients in Srinagar, J&K, and globally.",
  },
  {
    question: "Where is EASYIO Technologies located?",
    answer: "EASYIO Technologies is headquartered in Srinagar, Jammu and Kashmir, India. We serve clients across all localities in Srinagar including Lal Chowk, Karan Nagar, Raj Bagh, Bemina, Dalgate, and throughout Kashmir, as well as clients globally.",
  },
  {
    question: "What makes EASYIO Technologies the best software company in Kashmir?",
    answer: "EASYIO Technologies stands out as the best software company in Kashmir due to our experienced development team, cutting-edge technology stack, proven track record of successful projects, affordable pricing, excellent customer support, and deep understanding of local business needs in Kashmir and J&K region.",
  },
  {
    question: "Do you provide software services across all of Kashmir?",
    answer: "Yes, we provide software development services across entire Kashmir valley including Srinagar, Anantnag, Baramulla, Pulwama, Budgam, Kupwara, Bandipora, Ganderbal, Kulgam, Shopian, and all districts of Jammu and Kashmir.",
  },
  // Web Development FAQs
  {
    question: "Do you provide web development services in Srinagar?",
    answer: "Yes, EASYIO Technologies is the leading web development company in Srinagar, Kashmir. We create responsive, modern, SEO-friendly websites and web applications using the latest technologies like React, Next.js, and Node.js.",
  },
  {
    question: "How much does website development cost in Kashmir?",
    answer: "Website development costs in Kashmir vary based on project complexity. Basic websites start from INR 15,000-30,000, business websites from INR 30,000-75,000, e-commerce websites from INR 50,000-1,50,000, and custom web applications from INR 1,00,000 onwards. Contact us for a detailed quote.",
  },
  {
    question: "What technologies do you use for web development?",
    answer: "We use modern web technologies including React.js, Next.js, Vue.js, Angular for frontend; Node.js, Laravel, Django, PHP for backend; MongoDB, PostgreSQL, MySQL for databases; and AWS, Vercel, Digital Ocean for hosting.",
  },
  {
    question: "How long does it take to develop a website?",
    answer: "Website development timeline depends on complexity. A simple website takes 1-2 weeks, business website 2-4 weeks, e-commerce website 4-8 weeks, and custom web applications 8-16 weeks. We provide detailed timelines after project assessment.",
  },
  {
    question: "Do you offer website maintenance services in Kashmir?",
    answer: "Yes, we provide comprehensive website maintenance services in Kashmir including regular updates, security patches, content updates, performance optimization, backup management, and 24/7 technical support. Monthly maintenance packages start from INR 2,000.",
  },
  // App Development FAQs
  {
    question: "What is the cost of mobile app development in Srinagar?",
    answer: "Mobile app development costs in Srinagar range from INR 50,000-1,50,000 for simple apps, INR 1,50,000-3,00,000 for medium complexity apps, and INR 3,00,000-10,00,000+ for complex enterprise apps. Final cost depends on features, platforms, and design requirements.",
  },
  {
    question: "Do you develop Android and iOS apps?",
    answer: "Yes, we develop both Android and iOS applications. We offer native app development (Swift for iOS, Kotlin for Android) and cross-platform development using Flutter and React Native for cost-effective solutions that work on both platforms.",
  },
  {
    question: "What types of mobile apps do you develop in Kashmir?",
    answer: "We develop various types of mobile apps in Kashmir including e-commerce apps, booking apps, delivery apps, taxi apps, school/education apps, hospital/healthcare apps, restaurant apps, fitness apps, social networking apps, and custom business apps.",
  },
  {
    question: "How long does mobile app development take?",
    answer: "Mobile app development timeline varies by complexity. Simple apps take 4-8 weeks, medium apps 8-16 weeks, and complex apps 16-32 weeks. Cross-platform development with Flutter or React Native can reduce timeline by 30-40%.",
  },
  // ERP FAQs
  {
    question: "Can you develop custom ERP solutions?",
    answer: "Absolutely! EASYIO Technologies specializes in developing custom ERP solutions for businesses in Kashmir. Our ERP modules include HRMS, payroll, inventory, billing, accounting, attendance, purchase management, sales management, warehouse management, and CRM integration.",
  },
  {
    question: "What is the cost of ERP software in Kashmir?",
    answer: "ERP software costs in Kashmir depend on modules and customization. Basic ERP starts from INR 1,00,000, standard ERP from INR 2,00,000-5,00,000, and enterprise ERP from INR 5,00,000-20,00,000+. We also offer subscription-based cloud ERP starting from INR 5,000/month.",
  },
  {
    question: "Do you provide SAP ERP services in Srinagar?",
    answer: "Yes, we have SAP ERP consultants and developers in Srinagar who can help with SAP implementation, customization, and support. We also work with other ERP platforms like Oracle, Microsoft Dynamics, and Odoo.",
  },
  {
    question: "What ERP modules do you offer?",
    answer: "We offer comprehensive ERP modules including HRMS, Payroll Management, Attendance Management, Inventory Management, Billing & Invoicing, Accounting Integration, Purchase Management, Sales Management, Warehouse Management, CRM Integration, Project Management, and Analytics Dashboard.",
  },
  {
    question: "Can you implement cloud-based ERP for my business?",
    answer: "Yes, we specialize in cloud ERP implementation in Kashmir. Cloud ERP offers benefits like lower upfront costs, automatic updates, remote access, scalability, and better security. We can migrate your existing systems to cloud or deploy fresh cloud ERP solutions.",
  },
  // Industry-Specific FAQs
  {
    question: "Do you develop school management software in Kashmir?",
    answer: "Yes, we are the leading school ERP software provider in Kashmir. Our school management system includes student information, fee management, attendance tracking, exam management, timetable scheduling, parent portal, transport management, and library management modules.",
  },
  {
    question: "Can you develop hospital management software in Srinagar?",
    answer: "Yes, we develop comprehensive hospital management software in Srinagar including patient registration, appointment scheduling, OPD/IPD management, billing, pharmacy integration, lab management, inventory, and electronic health records (EHR) systems.",
  },
  {
    question: "Do you provide hotel management software in Kashmir?",
    answer: "Yes, we offer hotel management software for Kashmir's hospitality industry including room booking, reservation management, front desk operations, housekeeping, billing, restaurant POS integration, and online booking integration.",
  },
  {
    question: "Can you develop POS software for retail shops in Srinagar?",
    answer: "Yes, we develop modern POS (Point of Sale) software for retail businesses in Srinagar. Our POS solutions include billing, inventory management, barcode scanning, customer management, multiple payment modes, GST compliance, and detailed reporting.",
  },
  // Technical FAQs
  {
    question: "What programming languages do you use?",
    answer: "We work with multiple programming languages including JavaScript, TypeScript, Python, Java, PHP, Swift, Kotlin, Dart (Flutter), C#, and Go. Our choice depends on project requirements and best practices for each use case.",
  },
  {
    question: "Do you provide API development services?",
    answer: "Yes, we provide API development services including RESTful APIs, GraphQL APIs, third-party API integration, payment gateway integration, social media integration, and custom API solutions for connecting different systems and applications.",
  },
  {
    question: "Can you help with cloud migration?",
    answer: "Yes, we help businesses in Kashmir migrate to cloud platforms. We work with AWS, Microsoft Azure, Google Cloud, and Digital Ocean. Our services include assessment, planning, migration execution, and post-migration support.",
  },
  // Pricing & Quote FAQs
  {
    question: "How can I get a quote for my software project?",
    answer: "You can get a free quote by contacting us through our website contact form, emailing info@easyio.tech, or calling our office in Srinagar. We typically respond within 24 hours with a detailed proposal including timeline and cost estimates.",
  },
  {
    question: "Do you offer free consultations?",
    answer: "Yes, we offer free initial consultations to understand your project requirements. Our team will discuss your needs, suggest optimal solutions, and provide a detailed proposal with no obligation.",
  },
  {
    question: "What are your payment terms?",
    answer: "We offer flexible payment terms including milestone-based payments (typically 30% advance, 40% on development, 30% on delivery), monthly payment plans for maintenance services, and custom payment schedules for large projects.",
  },
  {
    question: "Do you offer monthly maintenance packages?",
    answer: "Yes, we offer monthly maintenance packages for websites and software. Basic maintenance starts from INR 2,000/month, standard from INR 5,000/month, and premium from INR 10,000/month, including updates, backups, security, and support hours.",
  },
  // Support FAQs
  {
    question: "Do you provide 24/7 support?",
    answer: "We provide business hours support (9 AM - 6 PM IST, Monday to Friday) for all clients. Premium and enterprise clients can opt for 24/7 support packages. We also have emergency support available for critical issues.",
  },
  {
    question: "What is your response time for support issues?",
    answer: "Our standard response time is within 4 hours during business hours. Critical issues are addressed within 1 hour. We use ticketing systems to track and resolve issues efficiently, ensuring minimal downtime for your business.",
  },
  {
    question: "Do you provide training for the software you develop?",
    answer: "Yes, we provide comprehensive training for all software we develop. This includes user training sessions, admin training, documentation, video tutorials, and ongoing support to ensure your team can effectively use the software.",
  },
  // Trust & Credibility FAQs
  {
    question: "How many years of experience does EASYIO Technologies have?",
    answer: "EASYIO Technologies has been delivering software solutions since 2024, with our team members having combined experience of many years in the IT industry. We have successfully completed 150+ projects for clients in Kashmir and across India.",
  },
  {
    question: "Can I see your portfolio of previous projects?",
    answer: "Yes, we have an extensive portfolio showcasing our web development, app development, ERP, and other projects. Visit our Our Work page or contact us for detailed case studies relevant to your industry.",
  },
  {
    question: "Do you sign NDAs and confidentiality agreements?",
    answer: "Yes, we take client confidentiality seriously. We are happy to sign NDAs (Non-Disclosure Agreements) before discussing project details. All our team members are bound by confidentiality clauses in their employment contracts.",
  },
  // E-commerce FAQs
  {
    question: "Can you develop an e-commerce website for my business in Kashmir?",
    answer: "Yes, we specialize in e-commerce website development in Kashmir. We build online stores using Shopify, WooCommerce, Magento, or custom solutions with features like product catalog, shopping cart, payment integration, order management, and shipping integration.",
  },
  {
    question: "Which payment gateways do you integrate?",
    answer: "We integrate all major payment gateways including Razorpay, Paytm, PayU, CCAvenue, Cashfree, Stripe, PayPal, and direct bank integration. We ensure PCI-DSS compliance for secure payment processing.",
  },
  // SEO & Digital Marketing FAQs
  {
    question: "Do you provide SEO services in Kashmir?",
    answer: "Yes, we provide comprehensive SEO services in Kashmir including on-page SEO, off-page SEO, technical SEO, local SEO, keyword research, content optimization, link building, and Google My Business optimization to improve your online visibility.",
  },
  {
    question: "How much does SEO cost in Srinagar?",
    answer: "SEO services in Srinagar start from INR 8,000/month for basic local SEO, INR 15,000-25,000/month for standard SEO, and INR 30,000+/month for comprehensive SEO campaigns. Pricing depends on competition, keywords, and scope of work.",
  },
  // Hosting & Deployment FAQs
  {
    question: "Do you provide web hosting services?",
    answer: "Yes, we provide managed web hosting services using reliable cloud platforms like AWS, DigitalOcean, and Vercel. Our hosting packages include SSL certificates, daily backups, security monitoring, and 99.9% uptime guarantee.",
  },
  {
    question: "Can you deploy software on my preferred hosting platform?",
    answer: "Yes, we can deploy applications on any hosting platform of your choice including AWS, Azure, Google Cloud, DigitalOcean, Hostinger, GoDaddy, or on-premise servers. We also provide guidance on choosing the best hosting for your needs.",
  },
  // Miscellaneous FAQs
  {
    question: "Do you work with startups in Kashmir?",
    answer: "Yes, we actively support startups in Kashmir with affordable development services, MVP development, technical consulting, and flexible payment terms. We have helped many local startups launch their digital products successfully.",
  },
  {
    question: "Can you work on existing projects or only new development?",
    answer: "We work on both new development and existing projects. Our services include bug fixes, feature additions, performance optimization, security updates, code refactoring, and complete redesign/redevelopment of existing applications.",
  },
  {
    question: "Do you offer dedicated development teams?",
    answer: "Yes, we offer dedicated development team services where you get exclusive access to developers working full-time on your project. This model is ideal for long-term projects or ongoing development needs.",
  },
  {
    question: "What is your project management approach?",
    answer: "We follow Agile methodology with iterative development, regular sprints, daily standups, and continuous client feedback. We use tools like Jira, Trello, Slack, and GitHub for project management and collaboration.",
  },
  {
    question: "How do you ensure code quality?",
    answer: "We ensure code quality through code reviews, automated testing, continuous integration, following coding standards, documentation, and using modern development practices. Our QA team performs thorough testing before any release.",
  },
];

// Social media profiles
export const socialProfiles = {
  facebook: "https://facebook.com/easyiotech",
  twitter: "https://twitter.com/easyiotech",
  linkedin: "https://linkedin.com/company/easyiotech",
  instagram: "https://instagram.com/easyiotech",
  youtube: "https://youtube.com/@easyiotech",
};

// Company information
export const companyInfo = {
  name: "EASYIO Technologies",
  legalName: "EASYIO Technologies Private Limited",
  description: "EASYIO Technologies is the leading software development company in Kashmir, specializing in enterprise software, custom ERP solutions, web development, mobile app development, e-commerce solutions, and digital transformation services in Srinagar, J&K.",
  foundingDate: "2024",
  founders: ["EASYIO Technologies"],
  employees: "150+",
  revenue: "Confidential",
  industry: "Information Technology",
  type: "Private Limited Company",
  website: "https://easyio.tech",
  slogan: "Best Software Company in Kashmir",
};

// Page-specific SEO configurations
export const pageSEOConfig = {
  home: {
    title: "EASYIO Technologies | Best Software Company in Kashmir | Web & App Development Srinagar",
    description: "EASYIO Technologies is the leading software company in Kashmir offering web development, app development, custom ERP solutions, and digital transformation services in Srinagar, J&K. Top-rated IT company with 150+ successful projects.",
    keywords: primaryKeywords,
  },
  about: {
    title: "About Us | EASYIO Technologies - Top IT Company in Kashmir",
    description: "Learn about EASYIO Technologies, the best software company in Kashmir. Our experienced team delivers cutting-edge web development, app development, and ERP solutions in Srinagar, J&K.",
    keywords: [...seoKeywords.bestTopIntent.slice(0, 10), ...seoKeywords.trustIntent.slice(0, 10)],
  },
  contact: {
    title: "Contact Us | EASYIO Technologies - Software Company Srinagar, Kashmir",
    description: "Contact EASYIO Technologies for software development, web development, app development, and ERP solutions in Kashmir. Get a free quote for your project. Based in Srinagar, serving all of J&K.",
    keywords: [...seoKeywords.nearMeLocality.slice(0, 15), "contact software company kashmir", "get quote software srinagar"],
  },
  erp: {
    title: "ERP Solutions | EASYIO Technologies - Best ERP Company in Kashmir",
    description: "EASYIO Technologies offers custom ERP solutions in Kashmir including HRMS, payroll, inventory, billing, and accounting modules. Best ERP software company in Srinagar, J&K.",
    keywords: seoKeywords.erp,
  },
  solutions: {
    title: "Software Solutions | EASYIO Technologies - Technology Services Kashmir",
    description: "Explore EASYIO Technologies' comprehensive software solutions including web development, app development, ERP systems, and digital transformation services in Kashmir, Srinagar.",
    keywords: [...seoKeywords.services.slice(0, 20), ...seoKeywords.bestTopIntent.slice(0, 10)],
  },
  webDevelopment: {
    title: "Web Development Company Kashmir | Website Design Srinagar - EASYIO Technologies",
    description: "Best web development company in Kashmir. Professional website design, e-commerce development, and custom web applications. Responsive, SEO-friendly websites by EASYIO Technologies Srinagar.",
    keywords: seoKeywords.webDevelopment,
  },
  appDevelopment: {
    title: "Mobile App Development Kashmir | Android & iOS Apps Srinagar - EASYIO Technologies",
    description: "Top mobile app development company in Kashmir. Android, iOS, Flutter, and React Native app development services. EASYIO Technologies - Best app developers in Srinagar, J&K.",
    keywords: seoKeywords.appDevelopment,
  },
  pricing: {
    title: "Software Development Pricing Kashmir | Get Quote - EASYIO Technologies",
    description: "Affordable software development pricing in Kashmir. Get free quotes for web development, app development, and ERP solutions. Transparent pricing from EASYIO Technologies Srinagar.",
    keywords: seoKeywords.pricingIntent,
  },
};

// Export keyword categories for use in components
export const keywordCategories = {
  bestTopIntent: "Best/Top Intent",
  nearMeLocality: "Near Me & Locality",
  erp: "ERP Solutions",
  appDevelopment: "App Development",
  webDevelopment: "Web Development",
  industrySpecific: "Industry-Specific",
  pricingIntent: "Pricing Intent",
  trustIntent: "Trust & Credibility",
  seoDigital: "SEO & Digital Marketing",
};
