/**
 * Comprehensive SEO Optimization for EASYIO Technologies
 * 100+ keywords targeting Kashmir, J&K, and global markets
 */

export const seoKeywords = {
  // Primary Brand Keywords
  brand: [
    "easyio technologies",
    "easyio",
    "easyio tech",
    "easyio kashmir",
    "easyio srinagar",
    "easyio jammu kashmir",
  ],

  // Location-Based Keywords (Kashmir/J&K Focus)
  location: [
    "software company in kashmir",
    "best software company kashmir",
    "software company srinagar",
    "IT company kashmir",
    "IT company srinagar",
    "IT company jammu kashmir",
    "tech company kashmir",
    "tech company srinagar",
    "web development company kashmir",
    "web development company srinagar",
    "app development company kashmir",
    "app development company srinagar",
    "software development kashmir",
    "software development srinagar",
    "custom software kashmir",
    "custom software srinagar",
    "ERP development kashmir",
    "ERP development srinagar",
    "digital solutions kashmir",
    "digital solutions srinagar",
    "technology solutions kashmir",
    "technology solutions srinagar",
    "software services kashmir",
    "software services srinagar",
    "IT services kashmir",
    "IT services srinagar",
    "tech solutions kashmir",
    "tech solutions srinagar",
    "software firm kashmir",
    "software firm srinagar",
    "IT firm kashmir",
    "IT firm srinagar",
    "technology company J&K",
    "software company J&K",
    "IT company J&K",
    "web development J&K",
    "app development J&K",
    "best IT company kashmir",
    "top software company kashmir",
    "leading software company kashmir",
    "premium software company kashmir",
    "professional software company kashmir",
  ],

  // Service-Based Keywords
  services: [
    "web development",
    "web development services",
    "website development",
    "website creation",
    "best website creators",
    "website builders",
    "custom website development",
    "responsive web design",
    "web application development",
    "app development",
    "mobile app development",
    "iOS app development",
    "Android app development",
    "custom app development",
    "software development",
    "custom software development",
    "enterprise software development",
    "ERP solutions",
    "ERP development",
    "custom ERP solutions",
    "ERP implementation",
    "enterprise resource planning",
    "business software solutions",
    "enterprise architecture",
    "core enterprise architecture",
    "neural logic engines",
    "high-performance systems",
    "digital transformation",
    "digital solutions",
    "technology consulting",
    "IT consulting",
    "software consulting",
    "cloud solutions",
    "cloud development",
    "API development",
    "backend development",
    "frontend development",
    "full stack development",
    "e-commerce development",
    "e-commerce solutions",
    "online store development",
    "CMS development",
    "content management systems",
    "database development",
    "database solutions",
    "system integration",
    "software integration",
    "API integration",
    "third-party integration",
    "maintenance and support",
    "software maintenance",
    "technical support",
    "software updates",
    "bug fixes",
    "performance optimization",
    "SEO services",
    "search engine optimization",
    "digital marketing",
    "online marketing",
    "brand development",
    "UI/UX design",
    "user interface design",
    "user experience design",
    "graphic design",
    "logo design",
    "brand identity",
  ],

  // Industry-Based Keywords
  industries: [
    "software for healthcare",
    "healthcare software solutions",
    "software for education",
    "education software solutions",
    "software for retail",
    "retail software solutions",
    "e-commerce software",
    "software for manufacturing",
    "manufacturing software solutions",
    "software for finance",
    "finance software solutions",
    "banking software",
    "software for real estate",
    "real estate software solutions",
    "software for hospitality",
    "hospitality software solutions",
    "software for logistics",
    "logistics software solutions",
    "software for agriculture",
    "agriculture software solutions",
    "government software solutions",
    "enterprise software",
    "business software",
    "SaaS development",
    "software as a service",
    "cloud-based solutions",
  ],

  // Technical Keywords
  technical: [
    "React development",
    "Next.js development",
    "Node.js development",
    "Python development",
    "JavaScript development",
    "TypeScript development",
    "Java development",
    "PHP development",
    "Laravel development",
    "Django development",
    "Flask development",
    "Express.js development",
    "MongoDB development",
    "PostgreSQL development",
    "MySQL development",
    "Firebase development",
    "AWS development",
    "Azure development",
    "Google Cloud development",
    "Docker development",
    "Kubernetes development",
    "microservices architecture",
    "RESTful API development",
    "GraphQL development",
    "serverless development",
    "progressive web apps",
    "PWA development",
    "responsive design",
    "mobile-first design",
    "agile development",
    "scrum development",
    "devops services",
    "CI/CD implementation",
    "version control",
    "Git development",
    "code review",
    "quality assurance",
    "software testing",
    "automated testing",
    "performance testing",
    "security testing",
    "penetration testing",
    "code optimization",
    "database optimization",
    "server optimization",
    "load balancing",
    "scalability solutions",
    "high availability",
    "disaster recovery",
    "backup solutions",
    "data security",
    "cybersecurity",
    "encryption services",
    "SSL certificates",
    "HTTPS implementation",
    "GDPR compliance",
    "data privacy",
    "API security",
    "authentication systems",
    "authorization systems",
    "single sign-on",
    "multi-factor authentication",
  ],

  // Long-Tail Keywords
  longTail: [
    "best software company in kashmir for web development",
    "top web development company in srinagar",
    "affordable app development kashmir",
    "custom ERP solutions for businesses in kashmir",
    "professional website creators in srinagar",
    "experienced IT company in jammu kashmir",
    "reliable software development services kashmir",
    "best tech solutions provider in kashmir",
    "leading digital transformation company kashmir",
    "premium software services in srinagar",
    "trusted technology partner kashmir",
    "innovative software solutions kashmir",
    "cutting-edge technology services srinagar",
    "modern web development kashmir",
    "advanced app development srinagar",
    "enterprise software solutions kashmir",
    "scalable technology solutions J&K",
    "cost-effective software development kashmir",
    "quality software services srinagar",
    "expert developers in kashmir",
    "skilled programmers srinagar",
    "professional coders kashmir",
    "best development team J&K",
    "top-rated software company kashmir",
    "highly rated IT services srinagar",
    "customer-focused software solutions kashmir",
    "result-oriented development services J&K",
    "on-time project delivery kashmir",
    "budget-friendly software solutions srinagar",
    "premium quality development kashmir",
  ],

  // Competitor Comparison Keywords
  comparison: [
    "best software company kashmir vs others",
    "top IT company srinagar",
    "leading web development kashmir",
    "premier app development srinagar",
    "number one software company J&K",
    "most trusted tech company kashmir",
    "highest rated software services srinagar",
    "most experienced developers kashmir",
    "most innovative solutions srinagar",
    "best value software company kashmir",
  ],

  // Problem-Solving Keywords
  problemSolving: [
    "need a website",
    "want to create an app",
    "looking for software developers",
    "need custom software",
    "require ERP system",
    "want digital transformation",
    "need web development help",
    "looking for app developers",
    "require IT services",
    "need technology solutions",
    "want to modernize business",
    "need online presence",
    "require e-commerce solution",
    "want mobile app",
    "need software maintenance",
    "looking for tech support",
    "require system integration",
    "need API development",
    "want cloud migration",
    "require database solutions",
  ],
};

// Combined keywords array for easy access
export const allKeywords = [
  ...seoKeywords.brand,
  ...seoKeywords.location,
  ...seoKeywords.services,
  ...seoKeywords.industries,
  ...seoKeywords.technical,
  ...seoKeywords.longTail,
  ...seoKeywords.comparison,
  ...seoKeywords.problemSolving,
];

// Primary keywords for meta tags
export const primaryKeywords = [
  "software company in kashmir",
  "best software company kashmir",
  "web development srinagar",
  "IT company J&K",
  "best website creators",
  "app development kashmir",
  "easyio technologies",
  "custom ERP solutions",
  "enterprise software development",
  "digital transformation kashmir",
];

// Location data for local SEO
export const locationData = {
  name: "EASYIO Technologies",
  address: {
    streetAddress: "Srinagar",
    addressLocality: "Srinagar",
    addressRegion: "Jammu and Kashmir",
    postalCode: "190001",
    addressCountry: "IN",
  },
  geo: {
    latitude: "34.0837",
    longitude: "74.7973",
  },
  areaServed: [
    "Kashmir",
    "Srinagar",
    "Jammu and Kashmir",
    "J&K",
    "India",
    "Global",
  ],
  openingHours: "Mo-Fr 09:00-18:00",
  telephone: "+91-XXXXXXXXXX",
  email: "info@easyio.tech",
  url: "https://easyio.tech",
};

// Service categories for structured data
export const serviceCategories = [
  {
    name: "Web Development",
    description: "Custom website and web application development",
  },
  {
    name: "App Development",
    description: "Mobile and desktop application development",
  },
  {
    name: "ERP Solutions",
    description: "Enterprise Resource Planning systems",
  },
  {
    name: "Digital Transformation",
    description: "Complete digital transformation services",
  },
  {
    name: "Cloud Solutions",
    description: "Cloud-based infrastructure and services",
  },
  {
    name: "Consulting",
    description: "Technology and IT consulting services",
  },
];

// FAQ data for FAQ schema
export const faqData = [
  {
    question: "What services does EASYIO Technologies offer?",
    answer:
      "EASYIO Technologies offers comprehensive software development services including web development, mobile app development, custom ERP solutions, digital transformation, cloud solutions, and technology consulting.",
  },
  {
    question: "Where is EASYIO Technologies located?",
    answer:
      "EASYIO Technologies is based in Srinagar, Jammu and Kashmir, India, serving clients globally.",
  },
  {
    question: "What makes EASYIO Technologies the best software company in Kashmir?",
    answer:
      "EASYIO Technologies combines cutting-edge technology, experienced developers, and a commitment to excellence, delivering high-performance enterprise systems and custom solutions that drive business growth.",
  },
  {
    question: "Do you provide web development services in Srinagar?",
    answer:
      "Yes, EASYIO Technologies specializes in web development services in Srinagar and across Kashmir, creating responsive, modern websites and web applications.",
  },
  {
    question: "Can you develop custom ERP solutions?",
    answer:
      "Absolutely! EASYIO Technologies specializes in developing custom ERP solutions tailored to your business needs, ensuring seamless integration and optimal performance.",
  },
  {
    question: "What technologies do you use for app development?",
    answer:
      "We use modern technologies including React Native, Flutter, iOS (Swift), Android (Kotlin), and cross-platform frameworks to develop high-quality mobile applications.",
  },
  {
    question: "Do you offer maintenance and support services?",
    answer:
      "Yes, we provide comprehensive maintenance and support services including software updates, bug fixes, performance optimization, and 24/7 technical support.",
  },
  {
    question: "How can I contact EASYIO Technologies?",
    answer:
      "You can contact us through our website contact form, email at info@easyio.tech, or visit our office in Srinagar, Jammu and Kashmir.",
  },
];

// Social media profiles
export const socialProfiles = {
  facebook: "https://facebook.com/easyiotech",
  twitter: "https://twitter.com/easyiotech",
  linkedin: "https://linkedin.com/company/easyiotech",
  instagram: "https://instagram.com/easyiotech",
  youtube: "https://youtube.com/@easyiotech",
};

// Company information
export const companyInfo = {
  name: "EASYIO Technologies",
  legalName: "EASYIO Technologies Private Limited",
  description:
    "EASYIO Technologies is a leading software development company in Kashmir, specializing in enterprise software, custom ERP solutions, web development, app development, and digital transformation services.",
  foundingDate: "2024",
  founders: ["EASYIO Technologies"],
  employees: "150+",
  revenue: "Confidential",
  industry: "Information Technology",
  type: "Private Limited Company",
  website: "https://easyio.tech",
};

